class Cities {
  static const List city = [
    {"country": "PS", "name": "Jabālyā", "lat": "31.5272", "lng": "34.48347"},
    {"country": "PS", "name": "Gaza", "lat": "31.50161", "lng": "34.46672"},
    {
      "country": "PS",
      "name": "Dayr al Balaḩ",
      "lat": "31.41834",
      "lng": "34.34933"
    },
    {
      "country": "PS",
      "name": "Bayt Lāhyā",
      "lat": "31.5464",
      "lng": "34.49514"
    },
    {
      "country": "PS",
      "name": "Bayt Ḩānūn",
      "lat": "31.5353",
      "lng": "34.53579"
    },
    {
      "country": "PS",
      "name": "Banī Suhaylā",
      "lat": "31.34337",
      "lng": "34.32337"
    },
    {
      "country": "PS",
      "name": "Al Fukhkhārī",
      "lat": "31.29278",
      "lng": "34.33061"
    },
    {
      "country": "PS",
      "name": "Al Burayj",
      "lat": "31.43944",
      "lng": "34.40306"
    },
    {
      "country": "PS",
      "name": "‘Abasān al Kabīrah",
      "lat": "31.31913",
      "lng": "34.34005"
    },
    {"country": "PS", "name": "Zubūbah", "lat": "32.54346", "lng": "35.22274"},
  ];
  List cities = [
    "Zefta, EG",
    "Ţūkh, EG",
    "Ţimā, EG",
    "Ţanţā, EG",
    "Ţāmiyah, EG",
    "Ţalkhā, EG",
    "Talā, EG",
    "Ţahţā, EG",
    "Sumusţā as Sulţānī, EG",
    "Sohag, EG",
    "Siwa Oasis, EG",
    "Sinnūris, EG",
    "Sīdī Sālim, EG",
    "Sīdī Barānī, EG",
    "Shubrā al Khaymah, EG",
    "Shirbīn, EG",
    "Shibīn al Qanāṭir, EG",
    "Shibīn al Kawm, EG",
    "Sharm el-Sheikh, EG",
    "Samannūd, EG",
    "Samālūţ, EG",
    "Rosetta, EG",
    "Ras Gharib, EG",
    "Rafaḩ, EG",
    "Quwaysinā, EG",
    "Quţūr, EG",
    "Qūş, EG",
    "Qinā, EG",
    "Qaşr al Farāfirah, EG",
    "Qalyūb, EG",
    "Nuwaybi‘a, EG",
    "Naja' Ḥammādī, EG",
    "Mīt Ghamr, EG",
    "Minyat an Naşr, EG",
    "Munūf, EG",
    "Maţāy, EG",
    "Mashtūl as Sūq, EG",
    "Mersa Matruh, EG",
    "Marsa Alam, EG",
    "Manfalūţ, EG",
    "Mallawī, EG",
    "Maghāghah, EG",
    "Madīnat Sittah Uktūbar, EG",
    "Madīnat an Naşr, EG",
    "Al ‘Āshir min Ramaḑān, EG",
    "Ash Shaykh Zuwayd, EG",
    "Kirdāsah, EG",
    "Kawm Umbū, EG",
    "Kawm Ḩamādah, EG",
    "Kafr Şaqr, EG",
    "Kafr az Zayyāt, EG",
    "Kafr ash Shaykh, EG",
    "Kafr ad Dawwār, EG",
    "Juhaynah, EG",
    "Girga, EG",
    "‘Izbat al Burj, EG",
    "Iţsā, EG",
    "Isnā, EG",
    "Idkū, EG",
    "Idfū, EG",
    "Ibshawāy, EG",
    "Ḩalwān, EG",
    "Hihyā, EG",
    "Ḩawsh ‘Īsá, EG",
    "Fuwwah, EG",
    "Farshūţ, EG",
    "Fāraskūr, EG",
    "Fāqūs, EG",
    "Damietta, EG",
    "Diyarb Najm, EG",
    "Disūq, EG",
    "Dishnā, EG",
    "Dikirnis, EG",
    "Dahab, EG",
    "Dayrūţ, EG",
    "Dayr Mawās, EG",
    "Damanhūr, EG",
    "Būsh, EG",
    "Port Said, EG",
    "Safaga, EG",
    "Bilqās, EG",
    "Bilbays, EG",
    "Basyūn, EG",
    "Banī Suwayf, EG",
    "Banī Mazār, EG",
    "Banhā, EG",
    "Zagazig, EG",
    "Awsīm, EG",
    "El-Tor, EG",
    "At Tall al Kabīr, EG",
    "Asyūţ, EG",
    "Aswan, EG",
    "Suez, EG",
    "As Sinbillāwayn, EG",
    "As Sallūm, EG",
    "Aş Şaff, EG",
    "Ash Shuhadā’, EG",
    "Ashmūn, EG",
    "Al Wāsiţah, EG",
    "Luxor, EG",
    "Al Qūşīyah, EG",
    "Al Quşayr, EG",
    "Al Qurayn, EG",
    "Al Qanāyāt, EG",
    "Al Qanāţir al Khayrīyah, EG",
    "Cairo, EG",
    "Al Minyā, EG",
    "Al Maţarīyah, EG",
    "Al Manzalah, EG",
    "Al Manşūrah, EG",
    "Al Minshāh, EG",
    "Al Maḩallah al Kubrá, EG",
    "Al Khuşūş, EG",
    "Al Khārjah, EG",
    "Al Khānkah, EG",
    "Giza, EG",
    "Al Jammālīyah, EG",
    "Ismailia, EG",
    "Alexandria, EG",
    "Al Ibrāhīmīyah, EG",
    "Al Ḩawāmidīyah, EG",
    "Al Ḩāmūl, EG",
    "Hurghada, EG",
    "Al Fayyūm, EG",
    "Al Fashn, EG",
    "Al Bawīţī, EG",
    "Al Balyanā, EG",
    "Al Bājūr, EG",
    "Al Badārī, EG",
    "Al ‘Ayyāţ, EG",
    "Arish, EG",
    "Al ‘Alamayn, EG",
    "Akhmīm, EG",
    "Ajā, EG",
    "Ad Dilinjāt, EG",
    "Abū Tīj, EG",
    "Abu Simbel, EG",
    "Abū Qurqāş, EG",
    "Abū Kabīr, EG",
    "Abū al Maţāmīr, EG",
    "Abnūb, EG",
    "Bi’r al ‘Abd, EG",
    "Az Zarqā, EG",
    "El Gouna, EG",
    "Makadi Bay, EG",
    "Ain Sukhna, EG",
    "New Cairo, EG",
    "Saint Catherine, EG",
    "Munshāt ‘Alī Āghā, EG",
    "Al-'Ubūr, EG",
    "Shūkat aş Şūfī, PS",
    "Rafaḩ, PS",
    "An Nuşayrāt, PS",
    "Khuzā‘ah, PS",
    "Khān Yūnis, PS",
    "Jabālyā, PS",
    "Gaza, PS",
    "Dayr al Balaḩ, PS",
    "Bayt Lāhyā, PS",
    "Bayt Ḩānūn, PS",
    "Banī Suhaylā, PS",
    "Al Fukhkhārī, PS",
    "Al Burayj, PS",
    "‘Abasān al Kabīrah, PS",
    "Zubūbah, PS",
    "Zaytā, PS",
    "Zaytā Jammā‘īn, PS",
    "Zawātā, PS",
    "Za‘tarah, PS",
    "Alei Zahav, PS",
    "Yiẕhar, PS",
    "Yaţţā, PS",
    "Yatmā, PS",
    "Yāsūf, PS",
    "Yāşīd, PS",
    "Yaqqir, PS",
    "Ya‘bad, PS",
    "Wādī Fūkīn, PS",
    "‘Ūrīf, PS",
    "Ūdalah, PS",
    "Turmus‘ayyā, PS",
    "Ţūlkarm, PS",
    "Ţūbās, PS",
    "Tayāsīr, PS",
    "Tarqūmyā, PS",
    "Ţammūn, PS",
    "Ţallūzah, PS",
    "Till, PS",
    "Talfīt, PS",
    "Taffūḩ, PS",
    "Suseya, PS",
    "Surif City, PS",
    "Surdā, PS",
    "Sīrīs, PS",
    "Sinjil, PS",
    "Silwād, PS",
    "Sīlat az̧ Z̧ahr, PS",
    "Sīlat al Ḩārithīyah, PS",
    "Sa‘īr, PS",
    "Shuqbā, PS",
    "Shūfah, PS",
    "Şaydā, PS",
    "Şarţah, PS",
    "Şarrah, PS",
    "Şānūr, PS",
    "Sannīryā, PS",
    "Sal‘it, PS",
    "Sālim, PS",
    "Salfīt, PS",
    "Şaffā, PS",
    "Sabasţīyah, PS",
    "Rummanah, PS",
    "Rūjayb, PS",
    "Rās Karkar, PS",
    "Rantīs, PS",
    "Rammūn, PS",
    "Rāmīn, PS",
    "Ramallah, PS",
    "Rāfāt, PS",
    "Rāfāt, PS",
    "Rābā, PS",
    "Quşrah, PS",
    "Qūşīn, PS",
    "Qīrah, PS",
    "Qibyah, PS",
    "Qedumim, PS",
    "Qedar, PS",
    "Qaţanah, PS",
    "Qaryūt, PS",
    "Qarne Shomeron, PS",
    "Qarāwat Banī Zayd, PS",
    "Qarāwat Banī Ḩasan, PS",
    "Qalqīlyah, PS",
    "Qalandiyā, PS",
    "Qaffīn, PS",
    "Qabāţīyah, PS",
    "Qabalān, PS",
    "Pesagot, PS",
    "Pedu’el, PS",
    "Ofra, PS",
    "Nūbā, PS",
    "Ni‘līn, PS",
    "Neve Daniel, PS",
    "Nazlat ‘Īsá, PS",
    "Naḩḩālīn, PS",
    "Bat A'in, PS",
    "Nablus, PS",
    "Mikhmās, PS",
    "Mislīyah, PS",
    "Mirkah, PS",
    "Mevo H̱oron, PS",
    "Banī Zayd ash Shārqīyah, PS",
    "Maythalūn, PS",
    "Masḩah, PS",
    "Mardā, PS",
    "Majdal Banī Fāḑil, PS",
    "Mādamā, PS",
    "Ma‘ale Mikhmas, PS",
    "Ma‘ale Efrayim, PS",
    "Ma‘ale Adummim, PS",
    "Al Lubban ash Sharqīyah, PS",
    "Kufayrit, PS",
    "Kokhav Ya‘aqov, PS",
    "Kifil Ḩāris, PS",
    "Ar Ramāḑīn, PS",
    "Qalqas, PS",
    "Imrīsh, PS",
    "Marāḩ Rabbāḩ, PS",
    "Dayr al ‘Asal al Fawqā, PS",
    "Bayt Ta‘mar, PS",
    "Bayt Ḩasan, PS",
    "Bayt ‘Awwā, PS",
    "Jannātah, PS",
    "Ash Shaykh Sa‘d, PS",
    "An Naşşārīyah, PS",
    "Kharbathā al Mişbāḩ, PS",
    "Al Majd, PS",
    "Karmah, PS",
    "Al Burj, PS",
    "Shuyūkh al ‘Arrūb, PS",
    "Khirbat Abū Falāḩ, PS",
    "Kharbathā Banī Ḩārith, PS",
    "Khārās, PS",
    "Khallat al Mayyah, PS",
    "Kefar ‘Eẕyon, PS",
    "Kefar Adummim, PS",
    "Kūbar, PS",
    "Karme Ẕur, PS",
    "Kafr Zībād, PS",
    "Kafr Thulth, PS",
    "Kafr Şūr, PS",
    "Kafr Rā‘ī, PS",
    "Kafr Qūd, PS",
    "Kafr Qallīl, PS",
    "Kafr Qaddūm, PS",
    "Kafr Mālik, PS",
    "Kafr Jammāl, PS",
    "Kafr Dān, PS",
    "Kafr ‘Ayn, PS",
    "Kafr al Labad, PS",
    "Kafr ad Dīk, PS",
    "Kafr ‘Abbūsh, PS",
    "Jūrīsh, PS",
    "Jūrat ash Sham‘ah, PS",
    "Al Judayyidah, PS",
    "Jīt, PS",
    "Jifnā, PS",
    "Jayyūs, PS",
    "Janīn, PS",
    "Jammā‘īn, PS",
    "Jalqamūs, PS",
    "Jalbūn, PS",
    "Al Jalamah, PS",
    "Jaba‘, PS",
    "Jaba‘, PS",
    "Immātīn, PS",
    "‘Immanu‘el, PS",
    "‘Illār, PS",
    "Iktābah, PS",
    "Idhnā, PS",
    "Ḩuwwārah, PS",
    "Ḩūsān, PS",
    "Ḩizmā, PS",
    "H̱innanit, PS",
    "Ḩāris, PS",
    "Har Gillo, PS",
    "H̱allamish, PS",
    "Ḩalḩūl, PS",
    "Ḩajjah, PS",
    "Ḩablah, PS",
    "Far‘ūn, PS",
    "Farkhah, PS",
    "Faqqū‘ah, PS",
    "Faḩmah, PS",
    "‘Ez Efrayim, PS",
    "Elqana, PS",
    "Efrata, PS",
    "Dūrā al Qar‘, PS",
    "Dūrā, PS",
    "Dūmā, PS",
    "Dhannābah, PS",
    "Dayr Sharaf, PS",
    "Dayr Qiddīs, PS",
    "Dayr Jarīr, PS",
    "Dayr Istiyā, PS",
    "Dayr Ibzī‘, PS",
    "Dayr Dibwān, PS",
    "Dayr Ballūţ, PS",
    "Dayr as Sūdān, PS",
    "Dayr al Ḩaţab, PS",
    "Dayr al Ghuşūn, PS",
    "Dayr Abū Mash‘al, PS",
    "Dayr Abū Ḑa‘īf, PS",
    "Brūqīn, PS",
    "Birqīn, PS",
    "Burqah, PS",
    "Burqah, PS",
    "Būrīn, PS",
    "Budrus, PS",
    "Bīr Zayt, PS",
    "Bīr Nabālā, PS",
    "Bil‘īn, PS",
    "Biddū, PS",
    "Bidyā, PS",
    "Bet Arye, PS",
    "Bazzāryah, PS",
    "Bayt Wazan, PS",
    "Bayt ‘Ūr at Taḩtā, PS",
    "Baytūnyā, PS",
    "Bayt Imrīn, PS",
    "Bayt Sūrīk, PS",
    "Bayt Sīrā, PS",
    "Bayt Sāḩūr, PS",
    "Bayt Qād, PS",
    "Bayt Liqyā, PS",
    "Bayt Līd, PS",
    "Bethlehem, PS",
    "Bayt Kāḩil, PS",
    "Bayt Jālā, PS",
    "Bayt ‘Anān, PS",
    "Baytīn, PS",
    "Bayt Ūmmar, PS",
    "Al Ittiḩād, PS",
    "Bayt Iksā, PS",
    "Bayt Ībā, PS",
    "Bayt Fūrīk, PS",
    "Bayt Fajjār, PS",
    "Bayt Duqqū, PS",
    "Bayt Dajan, PS",
    "Bayt Ūlā, PS",
    "Baytā al Fawqā, PS",
    "Battir, PS",
    "Battīr, PS",
    "Barţa‘ah ash Sharqīyah, PS",
    "Barqan, PS",
    "Bardalah, PS",
    "Bāqah ash Sharqīyah, PS",
    "Bāqat al Ḩaţab, PS",
    "Banī Na‘īm, PS",
    "Balāţah, PS",
    "Bal‘ā, PS",
    "‘Azzūn, PS",
    "Az Zāwiyah, PS",
    "Az̧ Z̧āhirīyah, PS",
    "Az Zabābidah, PS",
    "‘Azmūţ, PS",
    "‘Ayn Yabrūd, PS",
    "‘Ayn ‘Arīk, PS",
    "‘Aynabūs, PS",
    "Ūşarīn, PS",
    "‘Awartā, PS",
    "Aţ Ţīrah, PS",
    "‘Attīl, PS",
    "Aţ Ţaybah, PS",
    "Aţ Ţaybah, PS",
    "‘Aţārah, PS",
    "‘Aţārūt, PS",
    "As Sāwiyah, PS",
    "As Samū‘, PS",
    "‘Aşīrah ash Shamālīyah, PS",
    "‘Aşīrah al Qiblīyah, PS",
    "Ash Shuyūkh, PS",
    "Ash Shuhadā’, PS",
    "Arţās, PS",
    "Ar Rīḩīyah, PS",
    "‘Arrānah, PS",
    "Ar Rām wa Ḑāḩiyat al Barīd, PS",
    "‘Arrābah, PS",
    "Jericho, PS",
    "Al ‘Araqa, PS",
    "‘Aqrabā, PS",
    "‘Anzah, PS",
    "An Nuway‘imah, PS",
    "An Nazlah ash Sharqīyah, PS",
    "An Nāqūrah, PS",
    "An Nabī Ilyās, PS",
    "‘Anīn, PS",
    "‘Anātā, PS",
    "‘Anabtā, PS",
    "Al Yāmūn, PS",
    "Al Qubaybah, PS",
    "Al Mughayyir, PS",
    "Al Mughayyir, PS",
    "‘Almon, PS",
    "Al Midyah, PS",
    "Al Mazra‘ah ash Sharqīyah, PS",
    "Az Zaytūnīyah, PS",
    "Al Lubban al Gharbī, PS",
    "Al Khaḑir, PS",
    "Hebron, PS",
    "Al Judayrah, PS",
    "Al Jīb, PS",
    "Al Jāniyah, PS",
    "Al Hāshimīyah, PS",
    "Alfe Menashe, PS",
    "Al Faşāyil, PS",
    "Al Fandaqūmīyah, PS",
    "Al Bīrah, PS",
    "Al ‘Ayzarīyah, PS",
    "Al ‘Awjā, PS",
    "Al ‘Aţţārah, PS",
    "‘Ajjūl, PS",
    "‘Ajjah, PS",
    "‘Ibwayn, PS",
    "Abū Qashsh, PS",
    "Abū Dīs, PS",
    "‘Ābūd, PS",
    "Old City, PS",
    "An Naşr, PS",
    "‘Abasān al Jadīdah, PS",
    "Al Qarārah, PS",
    "Umm an Naşr, PS",
    "Juḩr ad Dīk, PS",
    "Az Zuwāydah, PS",
    "Al Muşaddar, PS",
    "Wādī as Salqā, PS",
    "Al Mughrāqah, PS",
    "East Jerusalem, PS",
    "Karney Shomron, PS",
    "al-Kum, PS",
    "Azun Atme, PS",
    "Jinşāfūţ, PS",
    "Banī Zayd, PS",
    "Az Za‘ayyim, PS",
    "Al ‘Ubaydīyah, PS",
    "Khallat an Nu‘mān, PS",
    "Khallat Ḩamāmah, PS",
    "Ad Dawḩah, PS",
    "Wādī Raḩḩāl, PS",
    "‘Arab ar Rashāydah, PS",
    "Bayt ‘Īnūn, PS",
    "Bayt Maqdum, PS",
    "Al Buq‘ah, PS",
    "Khallat ad Dār, PS",
    "Dayr Sāmit, PS",
    "Al Ḩīlah, PS",
    "Aş Şūrrah, PS",
    "Bayt ‘Amrah, PS",
    "Rābūd, PS",
    "Al Karmil, PS",
    "Khallat Şāliḩ, PS",
    "Bīr al Bāshā, PS",
    "Al Bādhān, PS",
    "‘Ayn al Bayḑā, PS",
    "Az Zubaydāt, PS",
    "Al Jiftlik, PS",
    "Khursā, PS",
    "Givat Zeev, PS",
    "Oranit, PS",
    "Itamar, PS",
    "Alon shvut, PS",
    "Bruchin, PS",
    "Geva Binyamin, PS",
    "Otniel, PS",
    "Beit El, PS",
    "Ganei Modi'in, PS",
  ];
}
